Fix duplicate host issue for aurora scheduler, DTCPIOPS-5221
aurora-scheduler/scheduler pull request #445
Opened 2022-06-03 18:57 UTC by lawwong1

### Description:

### Testing Done:

2022-06-06 23:35 UTC, lenhattan86 requested changes

2022-06-06 23:35 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +                    contains(offer.getOffer().getHostname()))
this line of code takes `O(n^2)` in time because contains take `O(n)`. Because a scheduling cycle matters in micro second to millisecond, it would be great if you can optimize this.

2022-06-06 23:35 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    List<String> extraOffers = response.hosts.stream().filter(host -> !mHosts.contains(host))
contains takes 'O(n)', we should avoid this.

2022-06-06 23:35 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
>              .filter(host -> !response.hosts.contains(host))
contains take O(n) here but it is only used for debugging. So, its somewhat acceptable.

2022-06-07 22:58 UTC, lawwong1 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
>              .filter(host -> !response.hosts.contains(host))
Re-write using map<host name, offerList>

2022-06-11 22:49 UTC, lenhattan86 approved these changes
great work Lawrence.
Can you add more details into description of this PR? change & test done.

2022-06-11 22:49 UTC, lenhattan86 commented on src/main/java/io/github/aurora/scheduler/offers/HttpOfferSetImpl.java
> +    Map<String, List<HostOffer>> offerMap = mOffers.stream().
great idea! this is what I was looking for.
groupby only takes O(n) so it must be fine to scale up.

2022-06-22 18:14 UTC, merged